### ISSUE TITLE
ImportError: No module named gmusicapi

### ISSUE THREAD

**Issue by ghost** [christopher-dG/pmcli#25]
I'm getting this error even though I have gmusicapi installed

``` Python
[cjb@pizza ~]$ gpymusic 
Traceback (most recent call last):
  File "/usr/local/bin/gpymusic", line 3, in <module>
    import client
  File "/home/cjb/.local/share/gpymusic/src/client.py", line 1, in <module>
    import common
  File "/home/cjb/.local/share/gpymusic/src/common.py", line 1, in <module>
    from gmusicapi import Mobileclient
ImportError: No module named 'gmusicapi'
[cjb@pizza ~]$
```

```
[cjb@pizza ~]$ pip install gmusicapi
Collecting gmusicapi
Collecting validictory!=0.9.2,>=0.8.0 (from gmusicapi)
Collecting proboscis>=1.2.5.1 (from gmusicapi)
Collecting mutagen>=1.34 (from gmusicapi)
Collecting python-dateutil!=2.0,>=1.3 (from gmusicapi)
  Using cached python_dateutil-2.6.0-py2.py3-none-any.whl
Collecting future (from gmusicapi)
Collecting mock>=0.7.0 (from gmusicapi)
  Using cached mock-2.0.0-py2.py3-none-any.whl
Collecting protobuf>=3.0.0 (from gmusicapi)
  Using cached protobuf-3.2.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting decorator>=3.3.1 (from gmusicapi)
  Using cached decorator-4.0.11-py2.py3-none-any.whl
Collecting oauth2client>=1.1 (from gmusicapi)
  Using cached oauth2client-4.0.0-py2.py3-none-any.whl
Collecting gpsoauth>=0.2.0 (from gmusicapi)
Collecting requests!=1.2.0,!=2.12.0,!=2.12.1,!=2.12.2,!=2.2.1,!=2.8.0,!=2.8.1,>=1.1.0 (from gmusicapi)
  Using cached requests-2.13.0-py2.py3-none-any.whl
Collecting MechanicalSoup>=0.4.0 (from gmusicapi)
  Using cached MechanicalSoup-0.6.0-py2.py3-none-any.whl
Collecting appdirs>=1.1.0 (from gmusicapi)
  Using cached appdirs-1.4.3-py2.py3-none-any.whl
Collecting six>=1.9.0 (from gmusicapi)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting funcsigs>=1; python_version < "3.3" (from mock>=0.7.0->gmusicapi)
  Using cached funcsigs-1.0.2-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock>=0.7.0->gmusicapi)
  Using cached pbr-2.1.0-py2.py3-none-any.whl
Collecting setuptools (from protobuf>=3.0.0->gmusicapi)
  Using cached setuptools-34.4.1-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from oauth2client>=1.1->gmusicapi)
  Using cached rsa-3.4.2-py2.py3-none-any.whl
Collecting httplib2>=0.9.1 (from oauth2client>=1.1->gmusicapi)
Collecting pyasn1-modules>=0.0.5 (from oauth2client>=1.1->gmusicapi)
  Using cached pyasn1_modules-0.0.8-py2.py3-none-any.whl
Collecting pyasn1>=0.1.7 (from oauth2client>=1.1->gmusicapi)
  Using cached pyasn1-0.2.3-py2.py3-none-any.whl
Collecting pycryptodomex>=3.0 (from gpsoauth>=0.2.0->gmusicapi)
Collecting beautifulsoup4 (from MechanicalSoup>=0.4.0->gmusicapi)
  Using cached beautifulsoup4-4.5.3-py2-none-any.whl
Collecting packaging>=16.8 (from setuptools->protobuf>=3.0.0->gmusicapi)
  Using cached packaging-16.8-py2.py3-none-any.whl
Collecting pyparsing (from packaging>=16.8->setuptools->protobuf>=3.0.0->gmusicapi)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Installing collected packages: validictory, proboscis, mutagen, six, python-dateutil, future, funcsigs, pbr, mock, appdirs, pyparsing, packaging, setuptools, protobuf, decorator, pyasn1, rsa, httplib2, pyasn1-modules, oauth2client, pycryptodomex, requests, gpsoauth, beautifulsoup4, MechanicalSoup, gmusicapi
Successfully installed MechanicalSoup-0.6.0 appdirs-1.4.3 beautifulsoup4-4.5.3 decorator-4.0.11 funcsigs-1.0.2 future-0.16.0 gmusicapi-10.1.2 gpsoauth-0.4.1 httplib2-0.10.3 mock-2.0.0 mutagen-1.37 oauth2client-4.0.0 packaging-16.8 pbr-2.1.0 proboscis-1.2.6.0 protobuf-3.2.0 pyasn1-0.2.3 pyasn1-modules-0.0.8 pycryptodomex-3.4.5 pyparsing-2.2.0 python-dateutil-2.6.0 requests-2.13.0 rsa-3.4.2 setuptools-34.4.1 six-1.10.0 validictory-1.1.1
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[cjb@pizza ~]$
```

```
[cjb@pizza ~]$ ls .local/lib/python2.7/site-packages/gmusicapi
appdirs.py  appdirs.pyc  clients  exceptions.py  exceptions.pyc  gmtools  __init__.py  __init__.pyc  protocol  session.py  session.pyc  test  utils  _version.py  _version.pyc
[cjb@pizza ~]$
```

**Comment by ghost** [comment]
I'm an idiot xD

I just needed to use python3 pip xD Sorry for posting this issue.

**Comment by christopher-dG** [comment]
Haha I was wondering for a moment how me updating the readme yesterday could have broken everything, glad you got it figured out :slightly_smiling_face:
