### ISSUE TITLE
Unable to start in virtualenv

### ISSUE THREAD

**Issue by tiberiuichim** [christopher-dG/pmcli#30]
I get this crash in a newly created virtualenv:

```
 ~/work/gpymusic   master *  bin/gpymusic-setup 
Traceback (most recent call last):
  File "bin/gpymusic-setup", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/tibi/work/gpymusic/bin/gpymusic-setup", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/tibi/work/gpymusic/bin/gpymusic-setup", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
...
  File "/home/tibi/work/gpymusic/bin/gpymusic-setup", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/tibi/work/gpymusic/bin/gpymusic-setup", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/tibi/work/gpymusic/bin/gpymusic-setup", line 4, in <module>
    __import__('pkg_resources').require('gpymusic==1.0.3')
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/__init__.py", line 971, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/__init__.py", line 816, in resolve
    requirements = list(requirements)[::-1]
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2886, in parse_requirements
    yield Requirement(line)
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2893, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 90, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 3511, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 3359, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 3964, in parseImpl
    loc, tokens = self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 3511, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 3359, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 3430, in parseImpl
    loc2 = e.tryParse( instring, loc )
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 1421, in tryParse
    return self._parse( instring, loc, doActions=False )[0]
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 2782, in parseImpl
    ret[k] = d[k]
  File "/home/tibi/work/gpymusic/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 405, in __setitem__
    self.__tokdict[k] = self.__tokdict.get(k,list()) + [_ParseResultsWithOffset(v,0)]
RecursionError: maximum recursion depth exceeded
```

**Comment by christopher-dG** [comment]
Hmmm, can't reproduce... Did you install with `pip install gpymusic`? Your directory structure says maybe not.

**Comment by tiberiuichim** [comment]
Indeed, installing in a brand new virtualenv and running ``pip install gpymusic`` works.

The above problem can be reproduced (at least that's what happens on my machine) by cloning the gpymusic repo from here, making a virtualenv in that folder (``virtualenv --clear --python=/usr/bin/python3 .``) and trying to run any gpymusic or gpymusic-setup script.

**Comment by tiberiuichim** [comment]
One more comment: there's a problem (a traceback with broken screen printing) when I try to run gpymusic but I haven't yet entered a new device id (so the placeholder is still in place). Fortunately, in that traceback, some valid device ids are printed so I just grabbed one of those.

**Comment by christopher-dG** [comment]
How convenient, I was the one who added the printing of device ids to gmusicapi :smile: 

Glad you got it figured out! I'll take a look into the crashes when I have time, since I get that some people prefer to install things manually.
