### ISSUE TITLE
Running gpymusic ends with a TypeError

### ISSUE THREAD

**Issue by tekknolagi** [christopher-dG/pmcli#43]
It looks like gpymusic can't read the OAuth credentials:

```
2017-10-29 22:52:21,012 - gmusicapi.Musicmanager2 (musicmanager:186) [WARNING]: could not retrieve oauth credentials from ''/home/max/.local/share/gmusicapi/oauth.cred''
Traceback (most recent call last):
  File "/usr/local/bin/gpymusic", line 4, in <module>
    __import__('pkg_resources').run_script('gpymusic==1.2.1', 'gpymusic')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/gpymusic-1.2.1-py3.5.egg/EGG-INFO/scripts/gpymusic", line 25, in <module>
  File "/usr/local/lib/python3.5/dist-packages/gpymusic-1.2.1-py3.5.egg/gpymusic/client.py", line 314, in __init__
  File "/usr/local/lib/python3.5/dist-packages/gpymusic-1.2.1-py3.5.egg/gpymusic/client.py", line 350, in gen_library
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi-10.1.2-py3.5.egg/gmusicapi/clients/musicmanager.py", line 287, in get_uploaded_songs
    to_return = [song for chunk in to_return for song in chunk]
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi-10.1.2-py3.5.egg/gmusicapi/clients/musicmanager.py", line 287, in <listcomp>
    to_return = [song for chunk in to_return for song in chunk]
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi-10.1.2-py3.5.egg/gmusicapi/clients/musicmanager.py", line 337, in _get_all_songs
    export_type)
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi-10.1.2-py3.5.egg/gmusicapi/clients/shared.py", line 84, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi-10.1.2-py3.5.egg/gmusicapi/protocol/shared.py", line 207, in perform
    req_kwargs = cls.build_request(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi-10.1.2-py3.5.egg/gmusicapi/protocol/shared.py", line 89, in build_request
    val = val(*args, **kwargs)
  File "<decorator-gen-68>", line 2, in dynamic_data
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi-10.1.2-py3.5.egg/gmusicapi/protocol/musicmanager.py", line 69, in pb
    msg = f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi-10.1.2-py3.5.egg/gmusicapi/protocol/musicmanager.py", line 652, in dynamic_data
    msg.client_id = client_id
  File "/usr/local/lib/python3.5/dist-packages/protobuf-3.4.0-py3.5.egg/google/protobuf/internal/python_message.py", line 662, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "/usr/local/lib/python3.5/dist-packages/protobuf-3.4.0-py3.5.egg/google/protobuf/internal/type_checkers.py", line 177, in CheckValue
    raise TypeError(message)
TypeError: None has type <class 'NoneType'>, but expected one of: (<class 'bytes'>, <class 'str'>)
```

**Comment by christopher-dG** [comment]
Have you run the oauth script?

**Comment by tekknolagi** [comment]
I did not, I don't think. As far as I can tell, that's not mentioned in the installation section. I'll give it a go.

Still, a better error message would be great.

**Comment by tekknolagi** [comment]
The oauth script looks like it works.

**Comment by christopher-dG** [comment]
Great! You're right, I hadn't really tested that.

**Comment by christopher-dG** [comment]
Great! You're right, I hadn't really tested that.
