### ISSUE TITLE
a valid MAC could not be determined

### ISSUE THREAD

**Issue by Suncatcher** [christopher-dG/pmcli#52]
I have the same error as [here](https://github.com/christopher-dG/gpymusic/issues/34), and [here](https://github.com/simon-weber/gmusicapi/issues/408), and [here](https://github.com/simon-weber/gmusicapi/issues/418). What is the reason of this error?

I have it on Kali Linux LiveCD inserted into physical laptop but can successfully login on AWS EC2 instance. Sounds like nonsence because laptop has physical NIC and instance is not.

I tried to replace `Mobileclient.FROM_MAC_ADDRESS` with MAC literal and that didn't help, but then script proposed me to replace it with some HEX value should have been working and it worked when I replaced Mobileclient.FROM_MAC_ADDRESS with it. 

But for another account this didn't work, so no consistency here.

What to do?

**Comment by eVen-gits** [comment]
Same issue:

```python
:~$ gpymusic-oauth-login

Visit the following url:
<redacted>
Follow the prompts, then paste the auth code here and hit enter: <redacted>
Traceback (most recent call last):
  File "/home/<redacted>/.local/bin/gpymusic-oauth-login", line 13, in <module>
    if mm.login():
  File "/home/<redacted>/.local/lib/python3.8/site-packages/gmusicapi/clients/musicmanager.py", line 97, in login
    self._perform_upauth(uploader_id, uploader_name))
  File "/home/<redacted>/.local/lib/python3.8/site-packages/gmusicapi/clients/musicmanager.py", line 109, in _perform_upauth
    raise OSError('a valid MAC could not be determined.'
OSError: a valid MAC could not be determined. Provide uploader_id (and be sure to provide the same one on future runs).
```
